// Giới hạn độ dài/số lượng trường của spec — dùng chung cho server (specService) và trình soạn thảo (maxlength).
export const SPEC_LIMITS = Object.freeze({
  slides: 60,
  deckTitle: 200,
  footer: 120,
  kicker: 60,
  title: 200,
  highlight: 100,
  subtitle: 400,
  caption: 200,
  notes: 4000,
  tags: 8,
  tag: 40,
  items: 12,
  itemTitle: 120,
  itemText: 400,
  itemValue: 40,
  stats: 8,
  statText: 16,
  statPrefix: 8,
  statSuffix: 12,
  statLabel: 160,
  steps: 10,
  columns: 3,
  colTitle: 100,
  colSubtitle: 60,
  points: 8,
  point: 200,
  quoteText: 600,
  quoteAuthor: 100,
  alt: 200,
  images: 6,
  videoTitle: 200,
  // Trang tự do (layout 'free'): phần tử đặt tự do (chữ, ảnh, video, bảng, hình khối) — toạ độ % của khung slide.
  elements: 30,
  elText: 1500,
  tableRows: 12,
  tableCols: 8,
  cell: 300,
  // Ảnh do AI tạo (Nano Banana) theo câu lệnh người dùng; tìm ảnh trên Internet theo từ khoá.
  aiPrompt: 1000,
  searchQuery: 100,
  // Dàn ý (bước duyệt trước khi dựng bài): mỗi trang là tiêu đề + các dòng nội dung sẽ hiển thị.
  outlineSlides: 40,
  outlinePoints: 12,
  outlinePoint: 400,
});
